### ISSUE TITLE
Auto import is messing with the types

### ISSUE THREAD

**Issue by danielmariz** [keajs/kea-typegen#29]
### Bug description (include screenshots or a GIF screencast)

I have a logic that imports a type from auth0-js package and other from the react-app-env.d.ts

my logic file
```
import { Auth0Error } from 'auth0-js'
//CredentialsType does not need to be imported from react-app-env

const authLogic = kea<authLogicType<CredentialsType, Auth0Error>>({
...
```

When I'm saving the file it auto generates the Type file with a weird import
```
//shouldn't be here
import { CredentialsType } from '../react-app-env.d'
import { Auth0Error } from '../../node_modules/@types/auth0-js/index.d'
//should extend the types passed authLogicType<CredentialsType, Auth0Error>
export interface authLogicType extends Logic { ...
```
and also it removes the types from the logic type that ends like that

````
const authLogic = kea<authLogicType>({
````
instead of as I described
```
const authLogic = kea<authLogicType<CredentialsType, Auth0Error>>({
```

and this puts the auto compiler in loop

### How to reproduce

1. scaffold a project using cra with typescript
2.  add a type from a installed package
3.  add a common type on react-app-env.d.ts file
4. create a logic extending those two types 

### Expected behavior
leave the logic as required
```
const authLogic = kea<authLogicType<CredentialsType, Auth0Error>>({
```

and stop auto importing those types and just extend them 
```
export interface authLogicType<CredentialsType, Auth0Error> extends Logic {

```
### Environment

- `kea-typegen` version: 1.1.5
- `kea` version: 2.4.0
- `typescript` version: 4.1.2

### Additional context
I'm using CRA with typescript scaffold
I've tried to upgrade for 1.1.5 after my [previous bug report](https://github.com/keajs/kea-typegen/issues/28) but I'm rolling back to my previous version of kea-typegen 0.7.1 where this error does not happen but ended up having to deal with that bug by commenting the piece of code connecting to the router

**Comment by danielmariz** [comment]
One thing I think would help with those auto generated types is adding `// @ts-nocheck` on top of them so we can avoid wrong auto compilation
I've tried to exclude them in the tsconfig but it seems to not be working 
```
"exclude": [
    "src/*Type.ts"
  ]
```

**Comment by mariusandra** [comment]
Hey,

I think you can get rid of the infinite loop (that's a bug and shouldn't happen to begin with) if you just keep your logic like this:

```
const authLogic = kea({})
```

However, why do you want to pass `CredentialsType` to the logic type, instead of letting it import it directly in the type?

I've rearchitected typegen to require as little manual intervention (e.g. passing types as arguments with `<>`), as possible. This is first for convenience, and second because with such type arguments you can't use parts of a type (`CredentialsType['provider']`) without running into typescript errors. Inside logicType.ts the shape of CredentialsType is unonownt if passed as an argument

**Comment by danielmariz** [comment]
Hum I see your point, I'm currently in v0.7.1 so I was trying to upgrade it and I didn't see you removed the necessity of passing down the arguments.
but will still having the same issue which is not importing for the right places

the CredentialsType shouldn't be imported because is declared globally if I understand it (or at least I don't need to import it inside of any of my ts files) 
and the Auth0Error should be imported from the auth0-js package instead of the '../../node_modules/@types/auth0-js/index.d'

But I will try to upgrade it again by the end of the week and see what need to be refactored for the new version
I was following what the docs and you video tutorial suggested before.

**Comment by danielmariz** [comment]
@mariusandra I working on all kea packages upgrade and still having this infinite loop while trying to compile my code

logicType still trying to import types from react-app-env.d.ts file and I'm getting this error

TypeScript error in /..project-path/src/store/authLogicType.ts(5,33):
[APP] File '/..project-path/src/react-app-env.d.ts' is not a module.  TS2306

and I got rid of the generic imports 

here is a sample code:

`
import { kea } from 'kea'

import { testLogicType } from './testType'

const testLogic = kea<testLogicType>({
    actions: {
        setUserInfo: (userInfo: UserInfoType) => ({ userInfo }),
    },
    reducers: {
        userInfo: [
            null as UserInfoType | null,
            { persist: true },
            {
                setUserInfo: (_, payload) => ({
                    ...payload.userInfo,
                    profile: payload.userInfo.profile,
                }),
                clearUserInfo: () => null,
            },
        ],
    },
})

`

generated type file

`
// Generated by kea-typegen on Thu, 09 Dec 2021 19:43:53 GMT. DO NOT EDIT THIS FILE MANUALLY.

import { Logic } from 'kea'

import { UserInfoType } from '../react-app-env.d'

export interface testLogicType extends Logic {
    actionCreators: {
        setUserInfo: (userInfo: UserInfoType) => {
            type: 'set user info (src.store.test)'
            payload: {
                userInfo: UserInfoType
            }
        }
    }
    actionKeys: {
        'set user info (src.store.test)': 'setUserInfo'
    }
    actionTypes: {
        setUserInfo: 'set user info (src.store.test)'
    }
    actions: {
        setUserInfo: (userInfo: UserInfoType) => void
    }
    constants: {}
    defaults: {
        userInfo: UserInfoType | null
    }
    events: {}
    key: undefined
    listeners: {}
    path: ['src', 'store', 'test']
    pathString: 'src.store.test'
    props: Record<string, unknown>
    reducer: (
        state: any,
        action: () => any,
        fullState: any,
    ) => {
        userInfo: UserInfoType | null
    }
    reducerOptions: {
        userInfo: {
            persist: boolean
        }
    }
    reducers: {
        userInfo: (state: UserInfoType | null, action: any, fullState: any) => UserInfoType | null
    }
    selector: (state: any) => {
        userInfo: UserInfoType | null
    }
    selectors: {
        userInfo: (state: any, props?: any) => UserInfoType | null
    }
    sharedListeners: {}
    values: {
        userInfo: UserInfoType | null
    }
    _isKea: true
    _isKeaWithKey: false
}
`

**Comment by danielmariz** [comment]
I got around it by double declaring the interfaces inside the logic file like;

```
interface GlobalUserInfoType extends UserInfoType {
```

Though, I still getting the compiling infinite loop

here is the log

```
[KEA] 🔄 Reloading...
[APP] Files successfully emitted, waiting for typecheck results...
[KEA] 🥚 message TS6194: Found 0 errors. Watching for file changes.
[APP] Compiled successfully!
[KEA] 🔥 Import added: src/store/pagesLogic.ts
[APP] Compiling...
[KEA] 🔄 Reloading...
[KEA] 🥚 message TS6194: Found 0 errors. Watching for file changes.
[APP] Compiled successfully!
[KEA] 🔥 Import added: src/store/pagesLogic.ts
[APP] Compiling...
[KEA] 🔄 Reloading...
[APP] Compiled successfully!
[KEA] 🥚 message TS6194: Found 0 errors. Watching for file changes.
[KEA] 🔥 Import added: src/store/pagesLogic.ts
[APP] Compiling...
[KEA] 🔄 Reloading...
[APP] Compiled successfully!
[KEA] 🥚 message TS6194: Found 0 errors. Watching for file changes.
[KEA] 🔥 Import added: src/store/pagesLogic.ts
[APP] Compiling...
[KEA] 🔄 Reloading...
[APP] Compiled successfully!
[KEA] 🥚 message TS6194: Found 0 errors. Watching for file changes.
[KEA] 🔥 Import added: src/store/pagesLogic.ts
[APP] Compiling...
[KEA] 🔄 Reloading...
[APP] Compiled successfully!
[KEA] 🥚 message TS6194: Found 0 errors. Watching for file changes.
[KEA] 🔥 Import added: src/store/pagesLogic.ts
[APP] Compiling...
[KEA] 🔄 Reloading...
[APP] Compiled successfully!
[KEA] 🥚 message TS6194: Found 0 errors. Watching for file changes.
[KEA] 🔥 Import added: src/store/pagesLogic.ts
```

pagesLogic.ts
```
import { kea } from 'kea'
// import { router } from 'kea-router'
import { pagesLogicType } from './pagesLogicType'
import userLogic from './userLogic'

const roleRoutes: any = {
    qsadmin: {},
    teacher: {},
    student: {
        '/': 'quizzes',
        '/practice': 'practice',
        '/practice/:courseId': 'practice',
        '/quiz': 'quiz',
        '/quiz/:quizId': 'quiz',
        '/settings': 'settings',
    },

}

const pagesLogic = kea<pagesLogicType>({
    path: ['containers', 'pages', 'main'],
    actions: {
        setPage: (page: string, params?: object) => ({ page, params }),
    },
    reducers: {
        page: [
            null as string | any,
            {
                setPage: (_, payload) => payload.page,
            },
        ],
        params: [
            {} as any,
            {
                setPage: (_, payload) => payload.params || {},
            },
        ],
    },
    urlToAction: ({ actions }) => {
        const mapping: any = {}
        const roleName = userLogic.values.roleName!
        const routes = roleRoutes[roleName.toLowerCase() as keyof typeof roleRoutes]
        for (const [paths, page] of Object.entries(routes)) {
            for (const path of paths.split('|')) {
                mapping[path] = (params: any) => actions.setPage(page as string, params)
            }
        }
        return mapping
    },
})

export default pagesLogic

```

**Comment by mariusandra** [comment]
Hey, I just published version 1.4.1, which lets you specify a list of paths that typegen will never import from.

Either set them in `.kearc`:

```
{
    "ignoreImportPaths": ["./src/react-app-env.d"]
}
```

or via the CLI:

```
kea-typegen --write --ignore-import-paths ./src/react-app-env.d
```

In addition to that, if you have any libraries in your tsconfig's `types` path, (e.g. `types: ['node', 'jest']`), then typegen will also automatically ignore all files imported from e.g. `./node_modules/@types/jest`. To disable this new default, pass `importGlobalTypes: true`.

Hope this helps somewhat!

**Comment by danielmariz** [comment]
@mariusandra in this new version I'm getting this weird error either on write or watch mode

```🥚 TypeScript Compiler API v4.5.3
👀 Starting TypeScript watch mode
🥚 message TS6194: Found 16 errors. Watching for file changes.
/Users/danielmariz/www/qs-client-app-v2/node_modules/yargs/build/index.cjs:2772
                throw err;
                ^

TypeError: Cannot read properties of undefined (reading 'map')
    at printToFiles (/Users/danielmariz/www/qs-client-app-v2/node_modules/kea-typegen/dist/src/print/print.js:60:19)
    at goThroughAllTheFiles (/Users/danielmariz/www/qs-client-app-v2/node_modules/kea-typegen/dist/src/typegen.js:81:51)
    at Object.host.afterProgramCreate (/Users/danielmariz/www/qs-client-app-v2/node_modules/kea-typegen/dist/src/typegen.js:61:17)
    at synchronizeProgram (/Users/danielmariz/www/qs-client-app-v2/node_modules/typescript/lib/typescript.js:120518:22)
    at Object.createWatchProgram (/Users/danielmariz/www/qs-client-app-v2/node_modules/typescript/lib/typescript.js:120437:9)
    at runTypeGen (/Users/danielmariz/www/qs-client-app-v2/node_modules/kea-typegen/dist/src/typegen.js:63:16)
    at Object.handler (/Users/danielmariz/www/qs-client-app-v2/node_modules/kea-typegen/dist/src/cli/typegen.js:17:30)
    at Object.runCommand (/Users/danielmariz/www/qs-client-app-v2/node_modules/yargs/build/index.cjs:446:48)
    at Object.parseArgs [as _parseArgs] (/Users/danielmariz/www/qs-client-app-v2/node_modules/yargs/build/index.cjs:2697:57)
    at Object.get [as argv] (/Users/danielmariz/www/qs-client-app-v2/node_modules/yargs/build/index.cjs:2651:25)

Node.js v17.0.1
error Command failed with exit code 1.```

**Comment by danielmariz** [comment]
meanwhile kea 1.4.0 compiles and generates the types though still on infinite importing loop

``` 
 Kea-TypeGen v1.4.0
🥚 TypeScript Config: ./tsconfig.json
🔥 Import added: src/store/pagesLogic.ts
🔥 Import added: src/store/pagesLogic.ts
🔥 Import added: src/store/pagesLogic.ts
🔥 Import added: src/store/pagesLogic.ts
🔥 Import added: src/store/pagesLogic.ts
🔥 Import added: src/store/pagesLogic.ts
🔥 Import added: src/store/pagesLogic.ts
🔥 Import added: src/store/pagesLogic.ts
🔥 Import added: src/store/pagesLogic.ts
```

**Comment by mariusandra** [comment]
Hey, 1.4.2 should fix the new bug. I'm still not sure why `pagesLogic` is stuck in a loop. I copied the code locally and everything was fine:

```
🦜 Kea-TypeGen v1.4.2
🥚 TypeScript Config: /Users/marius/Projects/Kea/kea-typegen/samples/tsconfig.json
🔥 Writing: samples/pagesLogicType.ts
🔥 Import added: samples/pagesLogic.ts
💚 13 logic types up to date!
```

Are you also running the latest TypeScript version? (4.5+)

**Comment by danielmariz** [comment]
Thanks @mariusandra for all the support again. now everything is working fine it seems.

I'm gonna upgrade the test within the new test package provided 

Cheers mate
