### ISSUE TITLE
kea-typegen write generates invalid syntax: `import { userAccountLogicType as  } from "..."`

### ISSUE THREAD

**Issue by deltaidea** [keajs/kea-typegen#34]
### Bug description (include screenshots or a GIF screencast)

I installed Kea into an existing TypeScript project, created a simple logic file with no actions or anything, and ran `key-typegen write`.

It generated a type file, but then generated invalid syntax for using it in the logic file. It then got stuck in a loop, overwriting the logic file again and again.

There's also Prettier mentioned in the logs. Not sure if `kea-typegen` is trying to be super smart and format everything correctly, that's cool.

![image](https://user-images.githubusercontent.com/4950036/144616471-0c2908bd-6712-42d2-9f15-5bfad557578e.png)

See actual behavior below.

### How to reproduce

Install Kea like this:
```
    "kea": "^2.5.4",
    "kea-loaders": "^0.5.1",
    "kea-typegen": "^1.3.0",
    "redux": "^4.1.2",
    "reselect": "^4.1.5",
    "react-redux": "^7.2.6",
```

Create tsconfig.json like this:

```json
{
  "compilerOptions": {
    "jsx": "react",
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "lib": ["ES2021", "DOM"],
    "module": "es6",
    "moduleResolution": "node",
    "noImplicitAny": true,
    "target": "ES2021"
  }
}
```

Create `.kearc` like this:

```json
{
  "rootPath": "./src",
  "typesPath": "./autogenerated-types"
}
```

Create a file `src/user-account.logic.ts` like this:

```typescript
import { kea } from "kea"

export const userAccountLogic = kea({
  actions: {},
  reducers: {},
  listeners: {},
})
```

Run `npx kea-typegen write`

---

Since prettier is mentioned in the logs, here's more from `package.json`:

```
    "eslint": "^7.28.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^3.4.0",
    "eslint-plugin-react-hooks": "^4.2.0",
    "prettier": "^2.5.0",
```

And here's `.prettierrc`:

```json
{
  "printWidth": 120,
  "semi": false
}
```

And `.eslintrc.json`:

```json
{
  "env": {
    "browser": true,
    "es2021": true
  },
  "root": true,
  "extends": [
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:prettier/recommended",
    "plugin:react-hooks/recommended"
  ],
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "project": "tsconfig.json",
    "sourceType": "module"
  },
  "plugins": ["@typescript-eslint"],
  "rules": {
    "indent": ["error", 2],
    "linebreak-style": ["error", "unix"],
    "semi": ["error", "never"]
  }
}
```

### Actual behavior

It generated file `autogenerated-types/user-account.logitType.ts`:

```typescript
// Generated by kea-typegen on Fri, 03 Dec 2021 13:51:33 GMT. DO NOT EDIT THIS FILE MANUALLY.

import { Logic } from 'kea'

export interface userAccountLogicType extends Logic {
  actionCreators: {}
  actionKeys: {}
  actionTypes: {}
  actions: {}
  constants: {}
  defaults: {}
  events: {}
  key: undefined
  listeners: {}
  path: ["user-account", "logic"]
  pathString: "user-account.logic"
  props: Record<string, unknown>
  reducer: (state: any, action: () => any, fullState: any) => {}
  reducerOptions: {}
  reducers: {}
  selector: (state: any) => {}
  selectors: {}
  sharedListeners: {}
  values: {}
  _isKea: true
  _isKeaWithKey: false
}
```

and changed `src/user-account.logic.ts` like this:

```typescript
import { kea } from "kea";
import { userAccountLogicType as  } from "../autogenerated-types/user-account.logicType";
export const userAccountLogic = kea({
    actions: {},
    reducers: {},
    listeners: {},
});
```

And got stuck in a loop, as shown on the screenshot above.

### Expected behavior

The command will generate valid TypeScript syntax.

### Environment

- `kea-typegen` version: 1.3.0
- `kea` version: 2.5.4
- `typescript` version: 4.5.2

**Comment by mariusandra** [comment]
Hey @deltaidea , thanks for reporting and apologies for the wait. Seems like TypeScript 4.5+ changed something which resulted in this behaviour. This should be fixed with TypeGen 1.4.0, out now.
